version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:eu-west-2:860061945305:task-definition/888336-HappyReturnsTask:1"
        LoadBalancerInfo:
          ContainerName: "package"
          ContainerPort: "9004"
        PlatformVersion: "LATEST"